### PR TITLE
Add unicorn worker settings.

### PR DESCRIPTION
**Pull request by andrekeller**
Add possibility to configure unicorn worker settings.

### CODE REVIEW

**Comment by andrekeller** [comment]
Hi,

I will gladly add the tests. 

default for timeout is 60, default for processes is nvcpu + 1, I'll add it to the pull request,

**Comment by andrekeller** [comment]
I rebased branch. Please advice if you'd like any further changes.

**Comment by spuder** [comment]
Thanks, looks great. 

Typically I've made the examples in the documentation match the default values. Is that something you could change quickly? If not, I can merge this as is.

**Comment by andrekeller** [comment]
ok, i fixed the timeout value. For the example of the processes I now use consistently 5. This is default if you have 4 cores. Other possibility would be to use something like 1 + $::processorcount. I'm not sure whats the better approach.

**Comment by spuder** [comment]
Great pull request, thanks so much.

**Pull request merged**
