### PR TITLE
fixes missing ssl_certificate when redirect_http_to_https

### LINKED ISSUE #126: when redirect_http_to_https is false the template gitlab-puppet.rb.erb ignores  ssl_certificate parameter
```
<% end %><% if @redirect_http_to_https == true -%>
nginx['redirect_http_to_https'] = <%= @redirect_http_to_https %>
nginx['ssl_certificate'] = '<%= @ssl_certificate -%>'
nginx['ssl_certificate_key'] = '<%= @ssl_certificate_key %>'
<% end -%>
```

This should probably be dependent on the ```external_url``` parameter starting with ```https```

### PR DESCRIPTION
**Pull request by timhughes**
fixes #126

### CODE REVIEW

**Comment by spuder** [comment]
I'd like to merge this, but I want to fix travis first so we can see if there are any big regressions.

**Comment by spuder** [comment]
Travis is still broken. Whats your confidence on this merge?

**Comment by timhughes** [comment]
Pretty confident, the tests i wrote were passing but I will take another
look with a fresh mind.

**Comment by timhughes** [comment]
I have had another look and I cannot see any issues. It works on my systems and I am pretty sure that the tests cover the requirements.

**Comment by spuder** [comment]
Great, I'll run some more testing on this. Thanks

**Comment by igalic** [comment]
@timhughes any news on this?

**Comment by timhughes** [comment]
@igalic As far as I am concerned this is good to go. The tests cover what I think the logic should be and they pass. I keep trying to get some work time to help @spuder clean up the rest of the travis tests so that he is happy to merge it but so far I haven't had the time.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab

**Pull request closed without merging**
